import type { Meta, StoryObj } from "@storybook/react";
import { useState } from "react";
import { AIInput } from "../ai-input";
import { DRAFT_TEXT, customActions } from "./AIInput.shared";

/* One page per AIInput variant, shown under "AIInput/Variants" in the
   sidebar. Static references for design review; the interactive playground
   is AIInput → Default. "!autodocs" keeps this folder from getting a
   second Docs page. */
const meta: Meta<typeof AIInput> = {
  title: "UI/AIInput/Variants",
  component: AIInput,
  tags: ["!autodocs"],
  parameters: {
    layout: "padded",
    backgrounds: { default: "lyra-shell" },
  },
};

export default meta;
type Story = StoryObj<typeof AIInput>;

function FilledDemo() {
  // Pre-filled so the "x" clear button — which only renders once there's
  // text to clear — is visible immediately without having to type first.
  const [value, setValue] = useState(DRAFT_TEXT);
  return <AIInput placeholder="Ask anything..." value={value} onChange={setValue} />;
}

export const States: Story = {
  name: "States (Empty, With Text, Disabled)",
  render: () => (
    <div className="w-[480px] flex flex-col gap-6">
      <AIInput placeholder="Ask anything..." />
      <FilledDemo />
      <AIInput
        disabled
        value="Processing your request..."
        placeholder="Ask anything..."
        helperText="Please wait while the AI responds."
      />
    </div>
  ),
};

export const SingleLine: Story = {
  name: "Single Line (Copilot Input)",
  /* `singleLine` lays the attach button, input, and submit/mic button out in
     one row instead of the default textarea-above/toolbar-below stack — a
     compact search-bar affordance for spaces like a Copilot side-panel
     footer, where a full multi-line composer would be too tall. No
     `helperText` on purpose: this variant is meant to read as a slim single
     row (pass `helperText` yourself if a usage still wants a caption). */
  render: () => (
    <div className="w-[480px]">
      <AIInput singleLine placeholder="Ask anything..." helperText="" />
    </div>
  ),
};

export const CustomActions: Story = {
  name: "Custom Actions",
  render: () => (
    <div className="w-[480px]">
      <AIInput placeholder="Ask anything..." actions={customActions} />
    </div>
  ),
};

export const NoAttachCustomHelper: Story = {
  name: "No Attach Button, Custom Helper Text",
  render: () => (
    <div className="w-[480px]">
      <AIInput
        showAttach={false}
        placeholder="Describe what you need..."
        helperText="Responses are generated by AI and may not always be accurate."
      />
    </div>
  ),
};
