import type { Meta, StoryObj } from "@storybook/react";
import { useState } from "react";
import { AIInput } from "../ai-input";
import { ConversationMessage } from "../conversation-message";
import { Mic, ImagePlus } from "lucide-react";
import { Tooltip } from "../tooltip";

const meta: Meta<typeof AIInput> = {
  title: "Atoms/AIInput",
  component: AIInput,
  tags: ["autodocs"],
  parameters: {
    layout: "padded",
    backgrounds: { default: "lyra-shell" },
  },
};

export default meta;
type Story = StoryObj<typeof AIInput>;

export const Default: Story = {
  name: "Default",
  render: () => {
    const [value, setValue] = useState("");
    const [submitted, setSubmitted] = useState<string[]>([]);
    return (
      <div className="w-[480px] flex flex-col gap-3">
        {submitted.length > 0 && (
          <div className="flex flex-col gap-2">
            {submitted.map((msg, i) => (
              <ConversationMessage key={i} role="user">{msg}</ConversationMessage>
            ))}
          </div>
        )}
        <AIInput
          value={value}
          onChange={setValue}
          onSubmit={(v) => { setSubmitted((s) => [...s, v]); setValue(""); }}
        />
      </div>
    );
  },
};

export const WithCustomActions: Story = {
  name: "With custom actions",
  render: () => (
    <div className="w-[480px]">
      <AIInput
        placeholder="Ask anything..."
        actions={
          <>
            <Tooltip content="Voice input" placement="top">
              <button
                type="button"
                aria-label="Voice input"
                className="flex h-8 w-8 items-center justify-center rounded-lyra-sm text-lyra-fg-secondary hover:bg-lyra-state-hover hover:text-lyra-fg-default transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lyra-border-focus"
              >
                <Mic className="h-4 w-4" strokeWidth={1.5} />
              </button>
            </Tooltip>
            <Tooltip content="Add image" placement="top">
              <button
                type="button"
                aria-label="Add image"
                className="flex h-8 w-8 items-center justify-center rounded-lyra-sm text-lyra-fg-secondary hover:bg-lyra-state-hover hover:text-lyra-fg-default transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lyra-border-focus"
              >
                <ImagePlus className="h-4 w-4" strokeWidth={1.5} />
              </button>
            </Tooltip>
          </>
        }
      />
    </div>
  ),
};

export const NoAttach: Story = {
  name: "No attach button",
  render: () => (
    <div className="w-[480px]">
      <AIInput showAttach={false} placeholder="Ask a question..." />
    </div>
  ),
};

export const CustomHelperText: Story = {
  name: "Custom helper text",
  render: () => (
    <div className="w-[480px]">
      <AIInput
        placeholder="Describe what you need..."
        helperText="Responses are generated by AI and may not always be accurate."
      />
    </div>
  ),
};

export const Disabled: Story = {
  name: "Disabled",
  render: () => (
    <div className="w-[480px]">
      <AIInput
        disabled
        value="Processing your request..."
        placeholder="Ask anything..."
        helperText="Please wait while the AI responds."
      />
    </div>
  ),
};
